name = "WordSearch"
uuid = "bc9bc190-06a8-4c61-b33b-656c0b162d31"
authors = ["Jarvist Moore Frost <jarvist@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
